<%@ page language="java" contentType="application/xml; charset=UTF-8"
    pageEncoding="UTF-8"%>

<members>
	<member>
		<id>id1</id>
		<name>둘리</name>
		<age>21</age>
		<addr>쌍문동</addr>
	</member>
	<member>
		<id>id2</id>
		<name>도우너</name>
		<age>11</age>
		<addr>방배동</addr>
	</member>
	<member>
		<id>id3</id>
		<name>또치</name>
		<age>9</age>
		<addr>대산동</addr>
	</member>
	<member>
		<id>id4</id>
		<name>마이콜</name>
		<age>17</age>
		<addr>성북동</addr>
	</member>
		<member>
		<id>id5</id>
		<name>고길동</name>
		<age>41</age>
		<addr>일원동</addr>
	</member>
</members>